ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-debian-trixie"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV \
    LANG='zh_CN.UTF-8' \
    LANGUAGE='zh.CN:zh' \
    LC_ALL='zh_CN.UTF-8' \
    TZ='Asia/Shanghai'
WORKDIR $HOME

### Envrionment config
ENV DEBIAN_FRONTEND=noninteractive \
    SKIP_CLEAN=true \
    KASM_RX_HOME=$STARTUPDIR/kasmrx \
    DONT_PROMPT_WSL_INSTALL="No_Prompt_please" \
    INST_DIR=$STARTUPDIR/install \
    INST_SCRIPTS="/ubuntu/install/tools/install_tools_deluxe.sh \
                  /ubuntu/install/misc/install_tools.sh \
                  /ubuntu/install/chrome/install_chrome.sh \
                  /ubuntu/install/chromium/install_chromium.sh \
                  /ubuntu/install/firefox/install_firefox.sh \
                  /ubuntu/install/sublime_text/install_sublime_text.sh \
                  /ubuntu/install/vs_code/install_vs_code.sh \
                  /ubuntu/install/remmina/install_remmina.sh \
                  /ubuntu/install/only_office/install_only_office.sh \
                  /ubuntu/install/gimp/install_gimp.sh \
                  /ubuntu/install/ansible/install_ansible.sh \
                  /ubuntu/install/terraform/install_terraform.sh \
                  /ubuntu/install/cleanup/cleanup.sh"

# Copy install scripts
COPY ./src/ $INST_DIR

# Run installations
RUN \
  for SCRIPT in $INST_SCRIPTS; do \
    bash ${INST_DIR}${SCRIPT} || exit 1; \
  done && \
  $STARTUPDIR/set_user_permission.sh $HOME && \
  rm -f /etc/X11/xinit/Xclients && \
  chown 1000:0 $HOME && \
  mkdir -p /home/kasm-user && \
  chown -R 1000:0 /home/kasm-user && \
  rm -Rf ${INST_DIR}

RUN apt-get update

RUN apt-get -y --no-install-recommends install poppler-utils fonts-crosextra-caladea fonts-crosextra-carlito nautilus file-roller \
    gsfonts lcdf-typetools xfce4-taskmanager jq gfortran p7zip-full yaru-theme-gtk numix-gtk-theme zsh gnome-terminal \
    blackbird-gtk-theme darkmint-gtk-theme orchis-gtk-theme yaru-theme-icon xfwm4-theme-breeze suru-icon-theme xcursor-themes
RUN apt-get -y --no-install-recommends install xfce4-appmenu-plugin xfce4-datetime-plugin xfce4-fsguard-plugin \
    xfce4-smartbookmark-plugin xfce4-genmon-plugin xfce4-netload-plugin xfce4-systemload-plugin xfce4-whiskermenu-plugin \
    xfce4-clipman xfce4-goodies xfce4-notes xfce4-time-out-plugin xfce4-windowck-plugin xfce4-clipman-plugin xfce4-diskperf-plugin  \
    xfce4-indicator-plugin xfce4-notes-plugin xfce4-screensaver xfce4-timer-plugin xfce4-xkb-plugin xfce4-cpufreq-plugin \
    xfce4-docklike-plugin xfce4-panel-profiles xfce4-screenshooter xfce4-verve-plugin xfce4-cpugraph-plugin xfce4-eyes-plugin      xfce4-mount-plugin      xfce4-places-plugin   xfce4-sensors-plugin       
RUN apt-get -y --no-install-recommends install fcitx5 fcitx5-pinyin

RUN cd /tmp && curl -o rustdesk.deb -fsSL "https://github.com/rustdesk/rustdesk/releases/download/1.4.4/rustdesk-1.4.4-x86_64.deb"  && apt-get install --no-install-recommends -y ./rustdesk.deb && rm -f rustdesk.deb && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /var/cache/debconf/* /var/log/* /tmp/* /var/tmp/*

RUN echo "zh_CN.UTF-8 UTF-8" >> /etc/locale.gen
RUN locale-gen

# Userspace Runtime
ENV HOME /home/kasm-user 
WORKDIR $HOME
USER 1000

CMD ["--tail-log"]
